from typing import List, Dict, Any, Optional, Annotated
from typing_extensions import TypedDict
from pydantic import BaseModel, Field
import operator

class Errand(BaseModel):
    id: str = Field(description="Unique identifier for the errand (e.g., 'e1', 'e2')")
    description: str = Field(description="Original description of the errand")
    errand_type: str = Field(description="Type of errand (e.g., 'grocery', 'pharmacy', 'post_office')")
    
    # Context injected by Memory Agent
    preferred_location: Optional[str] = Field(None, description="Location retrieved from past user memory")
    
    # Enriched by Geo-Clustering Agent
    resolved_location: Optional[str] = Field(None, description="Resolved address or coordinates")
    estimated_duration_mins: Optional[int] = Field(None, description="Estimated time spent at the location")
    
    # Enriched by Temporal-Constraint Agent
    time_constraint: Optional[str] = Field(None, description="Explicit time constraints (e.g., 'before 3pm')")
    opening_hours: Optional[str] = Field(None, description="Opening hours if applicable")
    
    # Enriched by Dependency Agent
    dependencies: List[str] = Field(default_factory=list, description="IDs of errands that must be done before this one")

class AgentProposal(BaseModel):
    agent_name: str
    proposed_sequence: List[str]
    score_penalty: int = 0
    rationale: str

def merge_proposals(a: List[AgentProposal], b: List[AgentProposal]) -> List[AgentProposal]:
    """Reducer for the LangGraph state to gather parallel proposals."""
    return a + b

class ErrandState(TypedDict):
    """
    Represents the session memory for the LangGraph pipeline in the Agent Society.
    """
    user_input: str
    user_location: str
    errands: List[Errand]
    
    # Populated asynchronously by specialist agents
    proposals: Annotated[List[AgentProposal], merge_proposals]
    
    # The final output generated by the Orchestrator
    final_plan_sequence: List[str]
    final_plan_text: str
    explanation_trace: str
